### ISSUE TITLE
Массив пустых объектов crm.Contact.find

### ISSUE THREAD

**Issue by n0isy** [UsefulWeb/AmoCRM#10]
let contacts = await crm.request.get( '/api/v2/contacts' );
возвращает Контакты, со всей структурой.
let contacts = await crm.Contact.find();
возвращает
[ {}, {}, {}, {} ]
Количество объектов совпадает с количеством контактов, но объекты пустые.

**Comment by neizerth** [comment]
Это в консоли показывается? Свойства быть должны. Из-за того, что в сущностях применён шаблон Proxy на пустом объекте, кажется, что ничего нет. А на самом деле - есть :)
В общем, я вместо пустого объекта добавил EnttyTarget, с ним вывод будет восприниматься получше.

**Comment by faradaytrs** [comment]
Та же проблема со сделками, 
await this.crm.Lead.findById(id)  // { } 
в результате пустой объект

**Comment by neizerth** [comment]
@faradaytrs Он не пустой, в нём есть свойства. В консоли они правда не будут отображаться. В качестве варианта можно обратиться к 

```js
const lead = await crm.Lead.findById(id);

console.log( lead.attributes );
```
