### ISSUE TITLE
Какие планы на библиотеку?

### ISSUE THREAD

**Issue by chukaev** [UsefulWeb/AmoCRM#12]
Собираетесь поддерживать?
Как долго?
Зачем вам это?

**Comment by neizerth** [comment]
@chukaev 
Собираюсь поддерживать. Пишу документацию на новую версию. В будущих версиях будет ООП будет для всех сущностей в API.
Изначально писал для отработки полученных из книг знаний, когда готовился к собеседованию в Яндексе.
Зачем мне это сейчас? Закрываю гештальт - код написан, а без документации уже как чемодан без ручки :)
Ну и хочется сделать крутую популярную библиотеку для людей, купаться в лучах славы, держа в бокал шампанского в окружении куртизанок :)

**Comment by chukaev** [comment]
@neizerth Владимир, много энергии, тепла и любви тебе!

**Comment by neizerth** [comment]
@chukaev Спасибо огромное! :) Это очень взаимно!

**Comment by chukaev** [comment]
Кстати, ты в курсе что есть api/v3 ?

**Comment by neizerth** [comment]
@chukaev Посмотрю. Что-то интересное добавилось?

**Comment by chukaev** [comment]
Даааа сейчас скину доку

**Comment by neizerth** [comment]
Спасибо :)

**Comment by chukaev** [comment]
[Beta документация API v3.docx](https://github.com/UsefulWeb/AmoCRM/files/3189217/Beta.API.v3.docx)

**Comment by neizerth** [comment]
О, у меня прямо ранний доступ к API :) Спасибо!

**Comment by chukaev** [comment]
И тебе спасибо 😇
