### ISSUE TITLE
Периодически возвращает ошибку авторизации

### ISSUE THREAD

**Issue by faradaytrs** [UsefulWeb/AmoCRM#13]
При запросе данных через request.get возвращается ошибка авторизации. Приходится делать повторный запрос, иногда нужный ответ приходит с 5 раза. Проблема усугубляется тем, что amocrm блокирует частые запросы и есть риск не получить данные вообще. Не совсем понятно с чем это связано. Данные авторизации понятное дело все это время не меняются.
Если сессия не продлевается в нужный момент, тогда как убедиться в том, что сейчас можно делать запрос?

**Comment by faradaytrs** [comment]
Пример подключения:
domain: 'dgdfsf', //без amocrm.ru
            auth: {
                login: 'login@login.ru',
                hash: 'dc5556ddda0872342342347e86c16d5e876c2475b9', // API-ключ доступа
            },
Параметры переподключения не указаны.

**Comment by faradaytrs** [comment]
Я попытался исследовать проблему и понял, что несмотря на то, что connection:checkReconnect вызывается каждую минуту, connection:beforeReconnect не вызывается вообще (сессия выдается надолго?)

**Comment by neizerth** [comment]
@faradaytrs А можно информацию об ошибке?

```js
crm.on( 'error', console.log );
```
Что выдаёт в итоге?
Проблему с частыми запросами решена на уровне библиотеки: единовременно не выполняется более одного запроса к порталу, все остальные запросы становятся в очередь.

Возможно, у вас есть несколько экземпляров портала и происходит единовременное обращение?

**Comment by neizerth** [comment]
Сессии правда надолго хватает. Что-то около месяца или двух

**Comment by faradaytrs** [comment]
> Сессии правда надолго хватает. Что-то около месяца или двух

А если формируется новая сессия старая аннулируется? Как это работает? Я все равно не понимаю в чем у меня проблема. В остальном crm.on( 'error', console.log ); пробую

**Comment by neizerth** [comment]
Мне нужно описание ошибки, тогда смогу подсказать.
Старая сессия аннулируется. Работает это на cookie-файле. При авторизации формируется cookie, который используется для всех последующих запросов.

**Comment by faradaytrs** [comment]
В общем я вчера добавил логов на разные действия и сейчас вот утром пришел на работу.
Всю ночь каждые две секунды делался запрос (а он делался повторно каждый раз потому что возвращалась ошибка, запрос к apiv2/leads через request.get). В итоге мой лог вырос до 11 мегабайт. crm.on( 'error', console.log ) насколько я вижу не вызывался.
 {
  error: 'Неверный логин или пароль',
  error_code: '110',
  ip: '89.212.240.252',
  domain: 'globus2.amocrm.ru',
  server_time: 1559040905
}

**Comment by neizerth** [comment]
Можно ли пример кода с работой?

**Comment by faradaytrs** [comment]
```js
get = async (prop, params = {}) => {
        const query = queryString.stringify(params, {arrayFormat: 'index'});
        let result;
        do {
            result = await this.crm.request.get(`/api/v2/${prop}?${query}`);
            if (result.response != null) {
                //wrong password error
                log(`get ${prop}`, result.response, params);
            }
        } while (result.response != null);

        return result._embedded.items;
    };
```
Как то так

**Comment by faradaytrs** [comment]
```js
const leads = await this.get('leads' ,{
            status: [123, 142, 234234],
            limit_rows: 500,
            limit_offset: 0
        });
```

**Comment by faradaytrs** [comment]
Как можно это решить/обойти?

**Comment by neizerth** [comment]
Добавлю тесты, буду проверять

**Comment by Voron295** [comment]
Подтверждаю проблему. Некоторое время всё работает хорошо, потом начинает возвращать ошибку авторизации.

**Comment by neizerth** [comment]
@faradaytrs @Voron295 можно ли попросить вас добавить тестов для воспроизведения ошибки? Не могу пока повторить

**Comment by sarnakov** [comment]
Такая же ошибка возникает с любыми операциями с АМО, при запуске сервера все работает правильно какое-то время, а потом ошибка авторизации. Пока решаю проблему созданием нового экземпляра AmoCRM и функции connect при каждой операции с амо.

**Comment by Voron295** [comment]
@neizerth да тут любое действие под тест подходит. Я просто создаю экземпляр AmoCRM и через какое-то время пытаюсь создать Lead и сохранить его. В результате получаю ошибку, которая описывалась выше. Если выполнять запрос сразу после создания экземпляра - всё ок. То есть должно пройти некоторое время.
Возможно это amocrm делает куки недействительными после каких-либо действий например на их сайте. Тут ничего конкретно сказать не могу.

Кстати, пытался решить проблему, написать disconnect, а затем снова connect, но ошибка всё равно возникала. Изучив AmoConnection.js пришёл к выводу, что disconnect не трогает переменную this._isConnected, хотя должен приравнять её к false. А в функции connect стоит как раз проверка на эту переменную - по итогу получается что после disconnect заново законнектиться невозможно.

**Comment by neizerth** [comment]
@Voron295 А есть возможность засечь время? Хотя бы примерно, сколько проходит времени?

_isConnected поправил

**Comment by neizerth** [comment]
@faradaytrs @Voron295 Посмотрите, может ли это быть связано с превышением лимитов на запросы?

https://www.amocrm.ru/developers/content/api/recommendations

**Comment by neizerth** [comment]
Пока не могу повторить проблему. В течение часа крутил создание Лидов, их удаление и получение информации об аккаунте в цикле:

```
for ( let i = 0; i < 1000; i++ ) {
      try {
        const lead = new crm.Lead({
          name: 'Lead for deletion'
        });
        await lead.save();
        await delay( 1000 );
        await lead.remove();
        await delay( 1000 );
        const info = await crm.request.get( '/api/v2/account' );
        console.log({
          index: i + 1,
          info
        });
      }
      catch (error) {
        console.log({
          index: i + 1,
          error
        });
      }

      await delay( 1000 );
    }
```

У меня Amo валится только из-за следующей ошибки: AmoCRM connection many requests check

**Comment by faradaytrs** [comment]
@neizerth Не могу сказать точно сколько времени, нужно проверять, но это не связано с лимитами. У меня сервер в основном обрабатывает хуки с различных сервисов и создает лиды в амосрм, они приходят раз в час максимум, особенно по ночам. Попробую засечь время.

**Comment by faradaytrs** [comment]
```
[10:15:8] listening on *:5000
[10:15:10] [crm] connected
[10:20:37] Message sent to Maja1.lodvika@msn.com
[10:24:19] [jivosite hook] added to database
[10:24:19] [jivosite hook] xboyz@hotmail.com to be added to the system
[10:24:19] [jivosite hook] passed autoresponse stage, about to add new lead
[10:24:21] [jivosite hook] lead added 20355315
[10:25:1] [jivosite hook] added to database
[10:25:1] [jivosite hook] deparhjesse@gmail.com to be added to the system
[10:25:1] [jivosite hook] passed autoresponse stage, about to add new lead
[10:25:3] [jivosite hook] lead added 20256317
[10:25:37] [jivosite hook] added to database
[10:25:37] jivosite hook sjasinowsky@gmail.com already exists
[10:25:37] [client already exists] null {
  messages: [
    {
      timestamp: 1559128624,
      type: 'visitor',
      message: 'Hi\nI need to furnish a 7 bedroom home in South Africa. what is ' +
        'the minimum spend for a full order? I would like to come 15-17 ' +
        'July'
    }
  ],
  rate: null
} [
  {
    timestamp: 1559128624,
    type: 'visitor',
    message: 'Hi\nI need to furnish a 7 bedroom home in South Africa. what is ' +
      'the minimum spend for a full order? I would like to come 15-17 ' +
      'July'
  }
]
[10:55:3] [crm] get leads {
  error: 'Неверный логин или пароль',
  error_code: '110',
  ip: '88.212.240.252',
  domain: 'progress2.amocrm.ru',
  server_time: 1559184903
} {
  status: [
    20674270,
    20674273,
    20674288,
    22115713,
    22283386,
    22596196,
    23674579,
    23674879
  ],
  limit_rows: 500,
  limit_offset: 0
}
[10:55:4] [crm] get leads {
  error: 'Неверный логин или пароль',
  error_code: '110',
  ip: '88.212.240.252',
  domain: 'progress2.amocrm.ru',
  server_time: 1559184904
} {
  status: [
    20674270,
    20674273,
    20674288,
    22115713,
    22283386,
    22596196,
    23674579,
    23674879
  ],
  limit_rows: 500,
  limit_offset: 0
}
```

**Comment by faradaytrs** [comment]
У меня лог на 529мб, в данном примере от подключения 10:15 до первой ошибки 10:55 прошло 40 минут

**Comment by Voron295** [comment]
Тут дело явно не в лимитах, а скорее наоборот - в том, что запросы довольно редкие. Сейчас не могу протестировать, но проходило примерно 30 минут от коннекта до запроса, и запрос отваливался с этой ошибкой. То есть тестировать надо большие задержки между запросами.

**Comment by neizerth** [comment]
Подтверждаю, ошибку нашел при длительных паузах между запросами. Буду искать причину

**Comment by Voron295** [comment]
Мне кажется проблема где-то на стороне самой amocrm. Вообще целесообразней на мой взгляд будет переписать систему переподключения, чтобы она срабатывала при подобных ошибках, а не только по истечению куков.

**Comment by ppskmg** [comment]
Проблема по прежнему имеется, логинится успешно, а при следующем get пишет неверный логин и пас

.get( '/api/v2/account' )
.then( data => {
    console.log( 'Полученные данные', data ); << неверный логин или пароль
})
.catch( e => {
    console.log( 'Произошла ошибка', e );
})

если у кого нет такой проблемы дайте плиз линк на сборку

**Comment by faradaytrs** [comment]
Недавно разговаривал с разработчиков amocrm по телефону и заодно спросил про эту проблему. Мне сказали что с сессия живет максимум 15 минут.

**Comment by neizerth** [comment]
@faradaytrs 

Да, тоже обратил внимание на этот факт только недавно:
https://www.amocrm.ru/developers/content/api/auth/

При бездействии более 15 минут сессия погибает.

Исправлено, начиная с версии 1.0.13

Друзья, огромное спасибо за помощь!

@Voron295 @faradaytrs @sarnakov @ppskmg ❤️

**Comment by faradaytrs** [comment]
Проблема не исчезла, по прежнему возвращает ошибку авторизации вместо данных.

**Comment by neizerth** [comment]
@faradaytrs Это также происходит через 15 минут?

**Comment by faradaytrs** [comment]
Возможно я локально включаю сервер он выбивает сессию с продакшена, в любом случае разве это не должно отлавливаться и автоматически переподключаться?

**Comment by neizerth** [comment]
@faradaytrs переподключение автоматически работает только в двух случаях:
1. Если прошлый запрос был сделан более 15 минут назад
2. Если время жизни cookie истекло (около 4 лет)

**Comment by neizerth** [comment]
@faradaytrs Тесты на истечение 15-минутной сессии библиотека начиная с 1.0.13 проходит. Прошу прислать уточнение по проблеме

**Comment by faradaytrs** [comment]
> @faradaytrs переподключение автоматически работает только в двух случаях:
> 
> 1. Если прошлый запрос был сделан более 15 минут назад
> 2. Если время жизни cookie истекло (около 4 лет)
> 
> По идее, сессия не должна отзываться. По крайней мере, такой информации в документации я не видел.
> 
> Можно ли узнать, в какой момент и через сколько времени появляется ошибка авторизации?

Как вообще можно полагаться на 15 минут? Мне сказали примерно 15 минут. Почему бы просто не смотреть результат, если вместо результата ошибка то переподключаться и делать запрос заного? Этот подход подойдет всем и в любом ситуации.

**Comment by neizerth** [comment]
> Как вообще можно полагаться на 15 минут?

Выдержка из документации (https://www.amocrm.ru/developers/content/api/auth/):

![image](https://user-images.githubusercontent.com/1821976/60767886-c9bbaf00-a0c6-11e9-9998-0d8a68d6bd51.png)

> Почему бы просто не смотреть результат, если вместо результата ошибка то переподключаться и делать запрос заного? Этот подход подойдет всем и в любом ситуации.

Ошибка авторизации (110) может также происходить при смене пароля / удалении пользователя из CRM, поэтому на это надеяться, на мой взгляд, не лучший вариант.

После подключения, в cookie есть только информация о времени истечения cookie файла, но не о времени сессии.

**Comment by faradaytrs** [comment]
> Ошибка авторизации (110) может также происходить при смене пароля / удалении пользователя из CRM, поэтому на это надеяться, на мой взгляд, не лучший вариант.
Ну при смене пароля или удалении пользователя и дальнейшая авторизация не пройдет. Эти варианты легко отлавливаются, потому что делать запрос для повторной авторизации все равно надо. Зато текущий подход сразу имеет несколько минусов:
1. Если нам вдруг начнут выдавать сессии которые живут короче, то текущие проверки станут неактуальны и придется это исправлять на уровне библиотеки.
2. Если сессия по какой то причине отвалилась данные не добавяться/обновяться. В итоге получается что на библиотеку и встроенный механизм обновления сессии нельзя полагаться и все равно надо все перепроверять, иначе есть серьезный риск потерять данные.

Мне кажется если есть возможность все таки добавить данные в crm, то библиотека должна хотя бы попытаться это сделать. Если после получения ошибки еще и авторизация не проходит, тогда уже возвращать ошибку.

**Comment by neizerth** [comment]
@faradaytrs 
> 1. Если нам вдруг начнут выдавать сессии которые живут короче, то текущие проверки станут неактуальны и придется это исправлять на уровне библиотеки.

Я считаю, что если будут сессии с короткой жизнью, то разработчики AmoCRM должны будут предупредить об этом в API. В ином случае это будет перестраховка на все возможные случаи жизни. На мой взгляд, внедрять ли такую безопасность или нет - право каждого разработчика. К тому же степень перестраховки у каждого может быть разной. 

> 2. Если сессия по какой то причине отвалилась данные не добавятся/обновятся. В итоге получается что на библиотеку и встроенный механизм обновления сессии нельзя полагаться и все равно надо все перепроверять, иначе есть серьезный риск потерять данные.

Моя задача - обеспечить отсутствие этих «каких-либо причин», если они не связаны с действиями пользователя.

Что вообще значит «отвал сессии» с учётом документации тут  (https://www.amocrm.ru/developers/content/api/auth/):

1. Слишком редко делались запросы за определённый промежуток
2. Cookie истёк

Все остальные причины не покрыты документацией. Если текущее поведение библиотеки не обрабатывает эти два исключения, я обязательно исправлю эту ситуацию. Если есть также какое-то недокументированное **закономерное** поведение CRM, при котором подключение становится недействительным, его также я считаю правильным включить в библиотеку.

Все прочие ситуации и перестраховки каждый разработчик может внедрить самостоятельно. Если есть интерес, могу подумать над вопросом расширения функционала с помощью разработки API для данной библиотеки.

Мне важно сейчас понять в какой момент у вас возникают ошибки кода (выше просил листинги и логи). Мне важно понять закономерность возникновения ошибок. Вопросы развития библиотеки и расширения её функционала сторонними разработчиками предлагаю обсуждать в другой ветке.

**Comment by faradaytrs** [comment]
Я сегодня залогирую все шаги чтобы понять в чем проблема, к вечеру-завтра отпишусь

**Comment by faradaytrs** [comment]
[11:27:15] [crm] connected
[11:27:52] [crm] successfully added data
[11:55:0] [crm] library managed reconnection
[11:55:0] [crm] connected
[11:55:0] [crm] manual reconnect
[11:55:0] [crm] disconnected
[11:55:0] [crm] connected
[11:55:1] [crm] [crm] successfully fetched data
[11:55:1] [scheduler] scheduled 0 tasks

Вот пока что такая картина, library managed reconnection это connection:beforeReconnect. После автоматического переподключения все равно пришла ошибка авторизации, затем сработало ручное переподключение и только тогда данные добавились в систему

**Comment by neizerth** [comment]
А какая версия библиотеки сейчас у вас стоит? Начиная с 1.0.13 переподключение по таймеру не должно работать. Сейчас переподключение срабатывает только при необходимости. То есть, если после прошлого запроса прошло больше 15 минут, ничего не происходит. Если при этом делается запрос, выполняется сначала переподключение, а затем и сам запрос

**Comment by faradaytrs** [comment]
> @faradaytrs
> А какая версия библиотеки сейчас у вас стоит? Начиная с 1.0.13 переподключение по таймеру не должно работать. Сейчас переподключение срабатывает только при необходимости. То есть, если после прошлого запроса прошло больше 15 минут, ничего не происходит. Если при этом делается запрос, выполняется сначала переподключение, а затем и сам запрос

Стоит 1.0.15

Действительно так и работает, проходит 15 минут, происходит переподключение, потом делается запрос и приходит ошибка авторизации (после свежего подключения).

**Comment by neizerth** [comment]
@faradaytrs 
Обновил библиотеку. Прошу проверить

**Comment by faradaytrs** [comment]
Вроде все нормально
