### ISSUE TITLE
Браузер генерирует OPTIONS запрос

### ISSUE THREAD

**Issue by gensli** [UsefulWeb/AmoCRM#17]
Здравствуйте. 
Заранее извиняюсь за, вероятно, глупый вопрос, но что-то я совсем поплыл.
Прям перед первым post, в connect() браузер делает OPTIONS, амо отвечает 405 Method Not Allowed и конец.
Тесты и вызов метод не из браузера само собой в норме.
Видимо, это из-за application/json (да и вообще амо могли бы на options и нормально ответить), но вряд ли же только у меня такая проблема. Наверняка, я что-то упускаю, но что?
Как вы дружите с CORS или только в серверной ноде используете библиотеку?

**Comment by neizerth** [comment]
@gensli Дмитрий, добрый день! Всё очень просто - библиотека предназначена для NodeJS. Передавать через браузер информацию об авторизационных данных в любом случае небезопасно. Поэтому пожалуйста, не делайте так :)

**Comment by gensli** [comment]
Ну у нас ключи амо лежат в базе с привязкой к пользователю и передаются по https, так что ничего более опасного, чем обычная аутентификация, не вижу. Если пользователь сам скомпрометирован, то уже без разницы.
Другие апи, которые мы используем нормально отвечают на options, так что проблем не возникало, а тут прям засада.
Но ваш подход я понял, нет браузера — нет проблем с cors :)

**Comment by neizerth** [comment]
@gensli Если вы делаете запросы из браузера, то библиотека передаёт вместе с ним информацию о cookie авторизации в портале. Эти заголовки можно проследить во вкладке Network, потом скопировать и гулять по порталу, манипулируя содержимым CRM.

Насколько знаю, на CORS AmoCRM не расчитан :(

**Comment by Vegys** [comment]
добрый вечер, тоже столкнулся с аналогичной проблемой http://joxi.ru/Vm6RGdxH4MQNjm , но если передаю домен в таком виде http://joxi.ru/L21dNRziRKvkJm ошибка cors пропадает, но сама авторизация все равно с ошибкой...
есть идеи как это можно обойти?
варианта на стороне бэкенда сделать нету, нужно на стороне фронта

**Comment by neizerth** [comment]
@Vegys только в том варианте, что вы описали. То есть, через прокси-сервер. И учтите, что если он не будет вам принадлежать, то вся информация о запросах (в том числе авторизации) будет проходить через третьих лиц, что крайне опасно

**Comment by Vegys** [comment]
@neizerth спасибо за быстрый ответ!
а то как я указал домен есть замечание, я имею ввиду воспримет ли код такой вид домена?
и даже если отправляю домен через прокси все равно пишет ошибку авторизации, что странно, так как данные правильные.
вижу в консоли http://joxi.ru/823Kq5xi9Rqdw2 и не понимаю в чем проблема, где ее искать.
нет идей случайно?)

**Comment by Vegys** [comment]
@neizerth а самое странное это если после неудавшегося запроса авторизации пройти напрямую по url api то статус авторизации успешен http://joxi.ru/LmG0bjecwa5JZ2

**Comment by neizerth** [comment]
@Vegys Я бы предложил это где-то вне репозитория обсуждать, так как это вопрос безопасности. Например, раньше данная библиотека поддерживала вход в портал по паролю, но потом разработчики Amo исключили эту возможность.

Если напрямую перейти, действительно проблем быть не должно, так как политика cors включается только при несоответствии доменов.

Чтобы гарантированно backend или прокси воспринимал вид домена, желательно, чтобы этот backend написали вы сами или понимали его работу :) Что там внутри heroku - только reverse ingeneering поможет

**Comment by Vegys** [comment]
ок, спасибо!
