### ISSUE TITLE
Решение поддерживается?

### ISSUE THREAD

**Issue by chukaev** [UsefulWeb/AmoCRM#18]
какие планы?

**Comment by neizerth** [comment]
Поддерживается 🙂 В планах сделать ООП вариант использования 🙂

**Comment by chukaev** [comment]
дев сильно отличается от основной ветки, когда будет мерж?

**Comment by neizerth** [comment]
@chukaev пока прогноз дать не могу. Толком весь код написан, очень много времени уходит на создание документации
