### ISSUE TITLE
Получение кода ответа при свободном запросе к CRM

### ISSUE THREAD

**Issue by zproxyz** [UsefulWeb/AmoCRM#19]
Невозможно получить код ответа при свободном запросе к CRM. 
Вот [тут](https://github.com/UsefulWeb/AmoCRM/blob/master/src/base/requests/domain/DomainRequest.js#L98) теряются параметры response и уже никак невозможно получить код ответа.

**Comment by neizerth** [comment]
@zproxyz Можете уточнить, что значит, «теряются»? Можно листинг? Какой ответ получаете и какой результат ожидаете?

**Comment by zproxyz** [comment]
@neizerth  В смысле, что когда мы обрабатываем промис, то на выходе получаем только данные, и уже никак не можем получить код ответа от сервера. "Теряются" значит, что на тот момент в коде, мы имеем все данные по респонсу, но когда обрабатываем через toJson handler, то на выходе получаем только данные из тела респонса.

**Comment by neizerth** [comment]
@zproxyz А в каких случаях нужен этот код? Можно несколько примеров? Просто понять, насколько это важная штука

**Comment by zproxyz** [comment]
@neizerth для удобства определения не успешных запросов при свободном запросе к CRM(через `request`), сейчас для определения ошибочного запроса приходится смотреть наличие свойства `title` со значением `Error` в теле ответа.

**Comment by neizerth** [comment]
@zproxyz я боюсь, придётся ломать обратную совместимость для такого или надо будет отдельный метод реализовать. А есть ли у вас мысли/предложения по этому поводу?

**Comment by neizerth** [comment]
@zproxyz в версии 2.x.x добавлен вывод кода ответа. Можете ознакомиться с документацией в README :)
