### ISSUE TITLE
При попытке подключения к AmoCRM получаю ошибку входа

### ISSUE THREAD

**Issue by uhomuho** [UsefulWeb/AmoCRM#21]
Много раз перепроверял вводимые данные, логин и ключ точно правильные, как и домен. При попытке подключения в npm runkit, всё работает прекрасно, с моего же сервера логин не проходит, единственная разница между ними в том, что в runkit я не ставил cors proxy, а у себя поставил, т.к. иначе запрос блокируется cors
![image](https://user-images.githubusercontent.com/45100335/79005472-591f5280-7b70-11ea-95cf-85f08b2dcd21.png)
![image](https://user-images.githubusercontent.com/45100335/79005732-f4b0c300-7b70-11ea-9eab-47ffb27e82c8.png)

**Comment by shamanov-d** [comment]
так либа вроде же серверная...
гугли отдельно по кросдоменным запросам, наврятли тут виновата либа...

**Comment by neizerth** [comment]
@uhomuho возможно из-за того, что ваш сервер находится на http протоколе. Сейчас поддерживается только http. Возможно, дело в этом. В любом случае, пока недостаточно отладочной информации. На фронте работу библиотеки не проверял. И не советую ей пользоваться на frontend, тк это небезопасно
