### ISSUE TITLE
Отсутствие метода patch

### ISSUE THREAD

**Issue by mr-Abdrahimov** [UsefulWeb/AmoCRM#24]
После компиляции не работает метод patch. В V4 API обновление контакта, к сожалению, происходят только через него.

**Comment by neizerth** [comment]
@mr-Abdrahimov Будет добавлено в следующей версии. Примерно неделя-две по времени

**Comment by neizerth** [comment]
@mr-Abdrahimov готово :) Хорошего дня!)
