### ISSUE TITLE
Отказ AmoCRM от API ключей

### ISSUE THREAD

**Issue by Devfw** [UsefulWeb/AmoCRM#25]
Доброго дня!
Я правильно понимаю, сейчас эта библиотека не актуальна и нужно пилить интеграцию на OAuth2 ?

[ОТКАЗ ОТ API КЛЮЧЕЙ И ПЕРЕХОД НА OAUTH АВТОРИЗАЦИЮ](https://www.amocrm.ru/developers/content/oauth/switch-over-oauth)

**Comment by neizerth** [comment]
@Devfw  Добрый день! Да, она подходит для старой версии протокола. Новую напишу в течение недели-двух

**Comment by Tyhur** [comment]
@neizerth как обстоят дела с новой версией? Может нужна какая-то помощь?

**Comment by neizerth** [comment]
@Tyhur пока занят своими проектами, не доходят руки. На выходных или середине след недели постараюсь выкатить релиз. Помощь всегда приветствуется) Скорее по документации будущих релизов. В общем-то, уже полтора года новая версия из-за отсутствия документации и примеров не выкатывается
