### ISSUE TITLE
Используйте Oauth вместо ключей API

### ISSUE THREAD

**Issue by memerson12** [UsefulWeb/AmoCRM#27]
AMO сообщил мне, что в будущем они планируют избавиться от системы аутентификации имени пользователя / хэша в пользу Oauth. Есть ли у этой библиотеки планы по поддержке OAuth?

**Comment by neizerth** [comment]
Дубликат #23

**Comment by neizerth** [comment]
@memerson12 реализовано в версии 2.0.0+ :) Хорошего дня!
