### ISSUE TITLE
Использование версии 1.x.x для AmoCRM API v2

### ISSUE THREAD

**Issue by magnum79** [UsefulWeb/AmoCRM#29]
Есть такая облачная платформа для хостинга NodeJS - Pipedream.com
Там отсутствует возможность настройки файла package.json
Я не могу указать, что мне нужна версия 1.0.18
Я просто пишу require('amocrm-js')
И вот недавно все сломалось, так как старый АПИ более не поддерживается.

Не знаю, по адресу ли я пишу, но можно ли создать отдельный npm-пакет для версий 1.x.x?
Либо мне следует сделать Fork и опубликовать собственный npm-пакет?
Как поступить правильнее?

P.S.: Я просто сдаюсь настраивать OAUTH авторизацию. Хочу пользоваться старым АПИ до последнего.

**Comment by neizerth** [comment]
@magnum79 Fork создам на выходных. Понятное описание авторизации по OAuth сделаю в блажайшее время

**Comment by neizerth** [comment]
@magnum79 если хотите, могу вам помочь разобраться с OAuth. Напишите мне в телегу: neizerth

**Comment by neizerth** [comment]
@magnum79 Подготовил для вас видео по настройке: https://youtu.be/eK7xYAbxJHo

По fork'у отпишусь позднее
