### ISSUE TITLE
При запросе на данные аккаунта приходит ошибка авторизации: 

### ISSUE THREAD

**Issue by Alex600** [UsefulWeb/AmoCRM#3]
Полученные данные { response:
   { error: 'Неверный логин или пароль',
     error_code: '110',
     ip: '88.212.240.252',
     domain: 'mydomen.amocrm.ru',
     server_time: 1536235109 } }

Так же при попытке создать сделку тоже ошибка авторизации

**Comment by neizerth** [comment]
Взято в работу

**Comment by neizerth** [comment]
@Alex600 прошу указать пример подключения. Скорее всего, имя домена передано как mydomain.amocrm.ru, а нужно только mydomain
