### ISSUE TITLE
Не обновляется токен авторизации (упрощенная авторизация)

### ISSUE THREAD

**Issue by skill-branch** [UsefulWeb/AmoCRM#32]
Не обновляется токен авторизации при упрощенной авторизации, так же нет возможности сохранить токен авторизации между сессиями (между перезагрузками приложения)

**Comment by amorev** [comment]
Добрый день! Внизу readme.md файла есть сноска как можно реализовать сохранение авторизации на стороне вашего приложения

### Сохранение авторизации между сессиями

Может быть полезным сохранять авторизацию между запусками приложения. Для этого есть событие `connection:newToken`, в которое приходит новый токен при каждом сохранении. 

Этот токен можно сохранять куда вам удобно (БД, файлы и тд). При инициализации соединения можно заранее установить токен для восстановления авторизации:
`crm.connection.setToken(currentToken, 0)`

Ниже пример реализации через сохранение в файл token.json который лежит рядом со скриптом
```javascript
  crm.on('connection:newToken', (token) => {
    fs.writeFileSync('./token.json', JSON.stringify(token.data))
  })
  try {
    const currentToken = require('./token.json')
    crm.connection.setToken(currentToken, 0)
  } catch (e) {
    // Token file not found
  }
```

**Comment by skill-branch** [comment]
Добрый день,  этот текст видел,  но из примера не совсем понятно как его использовать,  запускать приложение с протухшим кодом,  устанавливать токен и вызывать refreshToken,  ну и соответственно не совсем ясна реализация восстановления токена доступа при упрощенной авторизации похоже он все таки протухает примерно сутки спустя,  так как запущенный инстанс получает ошибку авторизации,  хотя приложение не было остановлено --Best wishes,  Team Skill-Branchskill-branch.ru15:03, 22 сентября 2020 г., Anton Morev <notifications@github.com>:
Добрый день! Внизу readme.md файла есть сноска как можно реализовать сохранение авторизации на стороне вашего приложения
Сохранение авторизации между сессиями
Может быть полезным сохранять авторизацию между запусками приложения. Для этого есть событие connection:newToken, в которое приходит новый токен при каждом сохранении.
Этот токен можно сохранять куда вам удобно (БД, файлы и тд). При инициализации соединения можно заранее установить токен для восстановления авторизации:
crm.connection.setToken(currentToken, 0)
Ниже пример реализации через сохранение в файл token.json который лежит рядом со скриптом
  crm.on('connection:newToken', (token) => {
    fs.writeFileSync('./token.json', JSON.stringify(token.data))
  })
  try {
    const currentToken = require('./token.json')
    crm.connection.setToken(currentToken, 0)
  } catch (e) {
    // Token file not found
  }

**Comment by amorev** [comment]
Вот тут однозначно сказать не могу - попробую воспроизвести на своих проектах. Благодарю за информацию!

**Comment by amorev** [comment]
Поймал проблему - если токен уже есть среди файлов, то не нужно указывать code при инициализации коннектора. Оставляйте только client_id, client_secret и redirect_uri в инициализации и тогда старый токен подхватится и обновится, на всякий случай:)

**Comment by Makaralex** [comment]
> 
> 
> Поймал проблему - если токен уже есть среди файлов, то не нужно указывать code при инициализации коннектора. Оставляйте только client_id, client_secret и redirect_uri в инициализации и тогда старый токен подхватится и обновится, на всякий случай:)

И после этого я ловлю ошибку
`TypeError: Cannot read property 'then' of undefined
    at AmoConnection.request (***\node_modules\amocrm-js\dist\base\AmoConnection.js:88:36)
    at request (***\node_modules\amocrm-js\dist\base\requests\ConnectionRequest.js:40:21)
    at AmoCRM.handler [as request] (***\node_modules\amocrm-js\dist\base\requests\ConnectionRequest.js:8:12)`

В итоге если оставлять, то у меня стоит так: сначала создаю экземпляр, указываю ему токен из сохранённых файлов, потом вызываю запрос к амо, ловлю ошибку, после чего делаю рефреш токена и тогда могу уже работать. 
Но встаёт вопрос: если отвалится авторизация во время работы? Да, токен у меня рефрешнется, а что быть с запросом? Как его перезапросить или типо того?
