### ISSUE TITLE
this.connectIfNeeded() иногда не возвращает Promise

### ISSUE THREAD

**Issue by mindesik** [UsefulWeb/AmoCRM#33]
Не уверен в какой именно момент, но вот что я сделал:

```javascript
crm.request.get('/api/v4/users').then(console.log).catch(console.error)
return crm.connection.getAuthUrl()
```

После этого я авторизируюсь и получаю эту ошибку в консоли запущенного сервера:

```
TypeError: this.connectIfNeeded(...).then is not a function
    at AmoConnection.request (node_modules/amocrm-js/dist/base/AmoConnection.js:88:37)
    at request (node_modules/amocrm-js/dist/base/requests/ConnectionRequest.js:40:21)
    at handler (node_modules/amocrmjs/dist/base/requests/ConnectionRequest.js:8:12)
```

Использую OAuth

**Comment by mindesik** [comment]
+ еще момент, если не выполнять никаких запросов (просто хочу авторизироваться на будущее), то oauth сервер не запускается.

**Comment by neizerth** [comment]
@mindesik ошибку исправил. Появляется ли проблема сейчас?

С запуском без запросов так и задумано - чтобы память лишний раз не расходовать. Явно можно вызвать crm.connect() - тогда запустится

**Comment by mindesik** [comment]
@neizerth Я правильно понял из видео, что после того как node процесс перезапускается, нужно снова вызывать окно авторизации?

**Comment by neizerth** [comment]
@mindesik после получения токена его можно сохранить и использовать уже только его

**Comment by westprophet** [comment]
У меня такая же проблема. 
Токен записывается в файл и по аналогии с вашим примером вытягивается.

Спустя время (1-2 дня) сам по себе сервер перестал обрабатывать запросы выкидывая такую ошибку
![image](https://user-images.githubusercontent.com/39632635/103281295-2574a900-49db-11eb-86f0-f315e52a2b3f.png)

`(async () => {
  crm.on('connection:error', () => console.log('AMOCRM: Ошибка соединения'));
  crm.on('connection:authError', () =>
    console.log('AMOCRM: Ошибка аутентификации')
  );
  crm.on('connection:beforeConnect', () =>
    console.log('AMOCRM: Соединяюсь...')
  );
  crm.on('connection:connected', () =>
    console.log('AMOCRM: Соединения успешно!')
  );
  crm.on('connection:error', () =>
    console.log('AMOCRM: Произошла ошибка соединения')
  );
  crm.on('connection:beforeRefreshToken', () =>
    console.log('AMOCRM: Обновление токена')
  );
  crm.on('connection:beforeFetchToken', () =>
    console.log('AMOCRM: Получение токена')
  );
  crm.on('connection:checkToken', () => {
    console.log('AMOCRM: Проверка токена');
  });

  crm.on('connection:newToken', (response) => {
    // console.log(JSON.stringify(response.data));
    try {
      // fs.writeFileSync('./token.json', JSON.stringify(response.data), 'utf8');
      fs.writeFileSync(
        './amocrm/token.json',
        JSON.stringify(response.data),
        // JSON.stringify(response.data),
        'utf8'
      );
      console.log('AMOCRM: Новый токен записан в файл');
    } catch (e) {
      console.error('AMOCRM:writeFileSync: ', e);
    }
  });

  try {
    const currentToken = require('./token.json');
    console.log('AMOCRM: Установка существующего токена');
    if (currentToken) crm.connection.setToken(currentToken);
    else throw '';
  } catch (e) {
    console.error('AMOCRM:Error:', e);
    console.log('AMOCRM: Попытка получить разрешения для авторизации...');
    try {
      const url = crm.connection.getAuthUrl();
      console.log('AMOCRM: Please confirm access: ', url);
    } catch (e) {
      console.error('AMOCRM:Error:', e);
    }
    try {
      await crm.connect();
    } catch (e) {
      console.error('Не удалось соединится', e);
    }
  }
})();`

**Comment by westprophet** [comment]
@neizerth каким образом можно хотя бы временно решить эту проблему?

**Comment by westprophet** [comment]
@neizerth как успехи? Если я могу как то поспособствовать по ускорению этого процесса, то скажите, я постараюсь помочь.

**Comment by westprophet** [comment]
@neizerth как скоро будет новый релиз? Я спрашиваю к тому что если не скоро то я буду вынужден переписать бекенд на своем проекте. Эта заявка весит с сентября прошлого года и как бы если у Вас не хватает времени то хотя бы дайте знать что бы люди не ждали решения данной проблемы.

**Comment by neizerth** [comment]
@westprophet внёс правки в 2.0.9. По идее, вылетать больше не должно

**Comment by westprophet** [comment]
@neizerth обновляюсь и тестирую

**Comment by westprophet** [comment]
@neizerth возможно это другая ошибка но, все же.  Сначала работало нормально, первые сутки, потом вот. 

![image](https://user-images.githubusercontent.com/39632635/108114399-69159600-70a1-11eb-910e-f212f433d21d.png)

Я попробую инициализировать токен еще раз, но думаю что возможно я неправильно использую. 

Вот кстати место где возникает ошибка. Походу ничего не приходит из API. Судя по всему. В чем может быть проблема?
![image](https://user-images.githubusercontent.com/39632635/108114770-e7723800-70a1-11eb-9f08-0e8d406673d2.png)

**Comment by westprophet** [comment]
@neizerth прошу прощения, есть какие то комментарии по этому поводу?

**Comment by neizerth** [comment]
@westprophet прошу создать отдельный тикет под задачу. Если ошибка не появляется, эту прошу закрыть

**Comment by westprophet** [comment]
@neizerth я не создавал тикет, но вроде все работает

**Comment by neizerth** [comment]
Окей, тогда этот закрываем) Прошу тогда отписать отдельно
