### ISSUE TITLE
Приходит пустой ответ на запрос с параметрами

### ISSUE THREAD

**Issue by margazun** [UsefulWeb/AmoCRM#37]
`const contacts = await crm.request.get('/api/v4/contacts?query=79130000000');`
`console.log('Contacts:\n', contacts);`

Приходит пустой ответ.
При отправке такого же запроса (https://domain.amocrm.ru/api/v4/contacts?query=79130000000) через браузер приходит правильный ответ с контактом.

**Comment by neizerth** [comment]
GET-параметры нужно передавать отдельным объектом:

```js
const contacts = await crm.request.get('/api/v4/contacts', {
    query: '79130000000'
});
```
