### ISSUE TITLE
Через время отваливает API и прекращает соединятся. Требуется переинициализация ключа.

### ISSUE THREAD

**Issue by westprophet** [UsefulWeb/AmoCRM#38]
@neizerth возможно это другая ошибка но, все же.  Сначала работало нормально, первые сутки, потом вот. Код который я бросал ранее, все еще актуален и не менялся.

![image](https://user-images.githubusercontent.com/39632635/108114399-69159600-70a1-11eb-910e-f212f433d21d.png)

Вот кстати место где возникает ошибка. Походу ничего не приходит из API. Судя по всему. В чем может быть проблема?
![image](https://user-images.githubusercontent.com/39632635/108115667-1c32bf00-70a3-11eb-9df0-d74c9ac4e5f5.png)

При переинициализации (удалении старого токена вручную и повторной авторизации через ссылку) все работает корректно на текущий момент. 

Но то что API отваливается само по себе конечно плоховато

**Comment by westprophet** [comment]
(async () => {
  crm.on('connection:error', () => console.log('AMOCRM: Ошибка соединения'));
  crm.on('connection:authError', () =>
    console.log('AMOCRM: Ошибка аутентификации')
  );
  crm.on('connection:beforeConnect', () =>
    console.log('AMOCRM: Соединяюсь...')
  );
  crm.on('connection:connected', () =>
    console.log('AMOCRM: Соединения успешно!')
  );
  crm.on('connection:error', () =>
    console.log('AMOCRM: Произошла ошибка соединения')
  );
  crm.on('connection:beforeRefreshToken', () =>
    console.log('AMOCRM: Обновление токена')
  );
  crm.on('connection:beforeFetchToken', () =>
    console.log('AMOCRM: Получение токена')
  );
  crm.on('connection:checkToken', () => {
    console.log('AMOCRM: Проверка токена');
  });

  crm.on('connection:newToken', (response) => {
    // console.log(JSON.stringify(response.data));
    try {
      // fs.writeFileSync('./token.json', JSON.stringify(response.data), 'utf8');
      fs.writeFileSync(
        './amocrm/token.json',
        JSON.stringify(response.data),
        // JSON.stringify(response.data),
        'utf8'
      );
      console.log('AMOCRM: Новый токен записан в файл');
    } catch (e) {
      console.error('AMOCRM:writeFileSync: ', e);
    }
  });

  try {
    const currentToken = require('./token.json');
    console.log('AMOCRM: Установка существующего токена');
    if (currentToken) crm.connection.setToken(currentToken);
    else throw '';
  } catch (e) {
    console.error('AMOCRM:Error:', e);
    console.log('AMOCRM: Попытка получить разрешения для авторизации...');
    try {
      const url = crm.connection.getAuthUrl();
      console.log('AMOCRM: Please confirm access: ', url);
    } catch (e) {
      console.error('AMOCRM:Error:', e);
    }
    try {
      await crm.connect();
    } catch (e) {
      console.error('Не удалось соединится', e);
    }
  }
})();

**Comment by neizerth** [comment]
@westprophet нужна детальная информация об ответе на запрос. Получится выложить в консоль?
