### ISSUE TITLE
request не дружелюбен для разработчика

### ISSUE THREAD

**Issue by BarkhatovN** [UsefulWeb/AmoCRM#43]
![image](https://user-images.githubusercontent.com/26570215/134722979-117adc33-a73c-4a49-95df-5f4898c18c65.png)
Делает невозможным выполнять запросы типа /api/v4/leads/${leadId}?with=catalog_elements
Приходится передавать через второй параметр { with: 'catalog_elements' }
Не было бы так больно, если бы при undefined '?' не добавлялся в конце всегда при GET-запросах

**Comment by neizerth** [comment]
Пока работает так

`crm.request.get( '/api/v4/{leadID}', { with: 'catalog_elements' });`

Добавлю парсинг адреса на будущее

**Comment by neizerth** [comment]
Спасибо! Реализовано в 3.0.0
