### ISSUE TITLE
Error with import

### ISSUE THREAD

**Issue by korovenko-tatyana** [UsefulWeb/AmoCRM#47]
Hi!
I add `amocrm-js` by `npm install amocrm-js` and now have version `3.0.2`
If I use `import Client from 'amocrm-js';` and then add constructor new Client(...), then error appears: 
_TypeError: amocrm_js_1.default is not a constructor_
But if I use `const Client = require('amocrm-js');` then no errors.
Please tell me the solution
![photo_2022-06-09_18-59-46](https://user-images.githubusercontent.com/17434916/172896092-2bd89c96-2864-4255-b887-b464ace67cd2.jpg)

**Comment by neizerth** [comment]
@korovenko-tatyana 
For TypeScript source files you need to write:
```ts
import Client from 'amocrm-js/src/Client';
```
Check this and if it throws an error, please reopen issue

**Comment by neizerth** [comment]
@korovenko-tatyana
fixed in v3.1.0

Now you need to use 
```js
import { Client } from 'amocrm-js'; // with brackets; There is no default import
```

**Comment by neizerth** [comment]
@korovenko-tatyana what version you have in package.lock?

**Comment by korovenko-tatyana** [comment]
@neizerth , "amocrm-js": "^3.1.1"

**Comment by neizerth** [comment]
@korovenko-tatyana please try with new 3.1.2 version. I make some fixes

**Comment by korovenko-tatyana** [comment]
@neizerth, thanks!
On versions 3.1.2 and 3.1.3 `import { Client } from 'amocrm-js';` works correctly, thanks!

But another bug:
I use in constructor also `auth: {code: ...}`
And after 
```
await client.connection.connect(); 
await client.token.fetch();
```
I get an error `Authorization code has been revoked` (API_RESPONSE_ERROR)
On version 3.0.1 there are no errors
![изображение](https://user-images.githubusercontent.com/17434916/173570249-48368bc1-0cde-4612-a98d-dbe6bfa8fdeb.png)

**Comment by neizerth** [comment]
@korovenko-tatyana 

you only need 

```js
await client.connection.connect(); 
```
This method gets token by auth code. It calls token.fetch() (https://github.com/UsefulWeb/AmoCRM/blob/29ece91d19b22e6741f0456dd81d29ecbe460763/src/common/Connection.ts#L88). 

Auth code can be used only once. When you're trying to get a token with used auth code, you will get an error, 'Authorization code has been revoked'. It's a part of AmoCRM API.

3.0.1 and 3.1.3-: These versions are the same for connections. I not make any changes.

If you get an error that not corresponding to this issue, please create a new one.

Have a nice day, and please star this project to make it most popular in The Galaxy!

**Comment by korovenko-tatyana** [comment]
@neizerth, thank you! All code works correctly)

It is very strange, but on version 3.0.1, where I used `const Client = require('amocrm-js');`, if don't add `await client.token.fetch();` then with any request (for example, `client.request.get('/api/v4/catalogs')`) you will get error `Unauthorized`. That's why I got this "bug" a few minutes ago on version 3.1.3)

Thanks for your fast changes and answers!

**Comment by neizerth** [comment]
@korovenko-tatyana 

```js
client.token.fetch()
```
Returns Promise. It means that you send async request to server and get answer sometimes.

```js
function onResponse(response) {
    // ...
}
client.token.fetch().then(onResponse)
```

If you don't make any actions before request complete, you simply can use await syntax:

```js
await client.token.fetch(); 
```

It means that you can make any actions after(!) you receive answer.

In your case, without await, you run two async requests and didn't wait for response:
1. First was successful
2. Second was in pending state
3. In this successful moment you calls API and it works before second client.token.fetch() fails
