### ISSUE TITLE
Ошибка при запросе сделок

### ISSUE THREAD

**Issue by capfsb** [UsefulWeb/AmoCRM#55]
При запросе сделок вместо возврата пустой коллекции скрипт падает с ошибкой. Ожидается пустой массив. Насколько я понял это со всеми подобными коллекциями такая ошибка

![image](https://user-images.githubusercontent.com/7259771/213353922-09fa83aa-cdf1-49b7-901e-89b37408d6f9.png)
```
client.leads.get({ query: 'ljflsadkjflk;asdflkjasdlkf' }).then(x => console.log(x.data))
```

**Comment by neizerth** [comment]
@capfsb Исправил в версии 3.4.1, прошу проверить. Большое спасибо за ожидание и использование ООП версии библиотеки!
