### ISSUE TITLE
Отвал сессии

### ISSUE THREAD

**Issue by manylov** [UsefulWeb/AmoCRM#7]
Реализовано ли переподключение?

**Comment by manylov** [comment]
у коллег сделано при потере сессии автоматическое перелогинивание и повтор последнего вызова, с возвратом результата. то есть снаружи перелогин и не виден. а если перелогин не удался (смена ключа и т п), то некий колбэк, в который можно например вставить отправку алерта в телегу или на мыло.

**Comment by neizerth** [comment]
Как насчёт такого варианта в будущем?

```javascript
crm.connect({
  reconnectAfterExpiration: true
});

crm.on('reconnect', callback);
crm.on('sessionExpired', callback)
```

**Comment by manylov** [comment]
еще crm.on('loginFail', callback) будет хорошо

**Comment by neizerth** [comment]
Готово! Переподключение работает автоматически. Добавлена поддержка событий:

```javascript
crm.on( 'connection:beforeReconnect' );
crm.on( 'connection:beforeConnect' );
crm.on( 'connection:authError' );
crm.on( 'connection:connected' );
crm.on( 'connection:error' );
```

На всякий случай, можно вручную установить время переподключения:

```javascript
crm.connection.reconnectAt( new Date(2020, 2, 3), delay, accuracyTime );
```

где *delay* - частота опроса (через сколько мс в очередной раз нужно проверить, пора ли переподключаться) и *accuracyTime* - точность (на сколько мс раньше истечения сессии должно состояться переподключение)

Возвращает обещание, которое сработает в момент успешного переподключения.

**Comment by manylov** [comment]
А что при переподключении выполняется запрос, на котором обнаружился отвал сессии?

**Comment by neizerth** [comment]
@manylov Сейчас сделано переподключение только в случае истёкшей сессии.

Если есть неполадки сети, то, по идее, они должны перехватываться в catch запросов:

```javascript
crm.request
.get( '/api/v2/account' )
.then( data => {
    console.log( 'Полученные данные', data );
})
.catch( e => {
    console.log( 'Произошла ошибка', e );
})
```

В случае неудачного запроса, необходимо вручную его повторить.

Ошибки соединения я не добавлял в тесты. Можно вас попросить добавить тесты? Если будут какие-то проблемы с кодом, я по тестам реализую функционал

**Comment by manylov** [comment]
вручную повторять неудобно, как раз втихую при отвале сессии желательно
повторить запрос и вернуть результат, чтобы для запращивающего вообще это
было гладко и на автомате.

пн, 28 янв. 2019 г. в 13:55, Vladimir Yazykov <notifications@github.com>:

**Comment by neizerth** [comment]
@manylov Окей! Прошу тогда сделать тесты и если есть пожелания по API, напишите сюда

**Comment by manylov** [comment]
Я попробую )

пн, 28 янв. 2019 г., 15:41 Vladimir Yazykov notifications@github.com:
