### ISSUE TITLE
еще работает?

### ISSUE THREAD

**Issue by Rotimi-Best** [UsefulWeb/AmoCRM#8]
работает модуль?

**Comment by neizerth** [comment]
Работает. Есть сомнения?

**Comment by Rotimi-Best** [comment]
я исп тоже самой пример на README но токе резултать было:

```javascript
const crm = new AmoCRM({
  domain: "user",
  auth: {
      login: "user@yahoo.com",
      hash: "sdfsldfk453405305sfkdf34853045lhgmfghdf",
  }
});

crm.Lead.find()
.then( leads => {
  console.log( "Найденное", leads ); // Найденное []
})

```
Массыв пустой хотя у меня есть лиды в аккуанте. Я тепер исп этот [пакет](https://github.com/Bolid1/npm-api-client-amocrm) он заработал для меня

**Comment by neizerth** [comment]
А crm.connect вызывали?

**Comment by Rotimi-Best** [comment]
Да. Я даже так сделал.

```javascript
const crm = new AmoCRM({
  domain: "user",
  auth: {
      login: "user@yahoo.com",
      hash: "sdfsldfk453405305sfkdf34853045lhgmfghdf",
  }
});

crm.connect().then(() => {
// мой hostname = user.amocrm.com а не user.amocrm.ru. Мб это из за этого не работает
  console.log(crm._request._queue._hostname) // user.amocrm.ru

  crm.Lead.find()
  .then( leads => {
      console.log( "Найденное", leads );
  })
});
```

**Comment by neizerth** [comment]
В новой версии (1.0.7) сделал возможность указания полного домена вида domain.amocrm.ru/domain.amocrm.com

Но боюсь, дело не в этом. 

```js
crm.connect().then( connected => console.log( connected ));
```

Выдаёт true?

**Comment by eugenmorozov** [comment]
Тоже есть сомнения в работоспособности. Использую примеры из readme:

const AmoCRM = require( 'amocrm-js' );

const crm = new AmoCRM({
    // логин пользователя в портале, где адрес портала domain.amocrm.ru
    domain: 'domain', // может быть указан полный домен вида domain.amocrm.ru, domain.amocrm.com
    auth: {
        login: 'mylogin',
        hash: 'mytesthash', // API-ключ доступа
    }
});

// Вход в портал
crm.connect();

crm.request
.get( '/api/v2/account' )
.then( data => {
    console.log( 'Полученные данные', data );
})
.catch( e => {
    console.log( 'Произошла ошибка', e );
})

отдаёт "Полученные данные {}"

На попытку получить сделки выдаёт пустой массив

**Comment by neizerth** [comment]
@eugenmorozov 
А что тесты выдают? Валятся ли с ошибками?

Портал зарегистрирован на amocrm.ru/.com?
Проплачен ли?

**Comment by n0isy** [comment]
По умолчанию там действительно .com , если написать домен верно, всё работает. Есть другой нюанс - connect не кидает throw, поэтому все в ступоре. )) В readme так же не описано, что connect возвращает булево.

**Comment by neizerth** [comment]
@n0isy как лучше, добавить throw или рассказать про статус соединения в throw?

**Comment by n0isy** [comment]
Как Вам будет удобнее. Думаю вполне логично кидать reject (throw) в connect. Там же promise. Я не то чтобы большой специалист в терминах.

**Comment by neizerth** [comment]
@n0isy добавил
Поправил домен по умолчанию на ru, теперь должно заработать. com-порталы уже нужно писать целиком
